--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.597.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 31.05.2021 15:06:03
-- Server version: 8.0.25
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Create table `schet`
--
CREATE TABLE schet (
  n int NOT NULL AUTO_INCREMENT,
  bank varchar(50) NOT NULL DEFAULT 'Не указано',
  numb varchar(50) NOT NULL,
  sost int NOT NULL DEFAULT 0,
  data date NOT NULL,
  cr enum ('Y', 'N') NOT NULL,
  summa float(12, 0) UNSIGNED DEFAULT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX idschet (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `postav`
--
CREATE TABLE postav (
  n int NOT NULL AUTO_INCREMENT,
  nazv varchar(500) NOT NULL DEFAULT 'Не указано',
  uradr varchar(500) NOT NULL DEFAULT 'Не указано',
  schet int DEFAULT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX idpostav (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Поставщики';

--
-- Create index `i4` on table `postav`
--
ALTER TABLE postav
ADD UNIQUE INDEX i4 (nazv);

--
-- Create foreign key
--
ALTER TABLE postav
ADD CONSTRAINT FKschetp FOREIGN KEY (schet)
REFERENCES schet (n);

--
-- Create table `klient`
--
CREATE TABLE klient (
  n int NOT NULL AUTO_INCREMENT,
  fio varchar(250) NOT NULL DEFAULT 'Не указано',
  adres varchar(500) DEFAULT NULL,
  schet int DEFAULT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX idclient (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `i3` on table `klient`
--
ALTER TABLE klient
ADD UNIQUE INDEX i3 (fio);

--
-- Create foreign key
--
ALTER TABLE klient
ADD CONSTRAINT FKschet FOREIGN KEY (schet)
REFERENCES schet (n);

--
-- Create table `firma`
--
CREATE TABLE firma (
  firma varchar(500) NOT NULL DEFAULT '',
  uradr varchar(500) NOT NULL DEFAULT '',
  telefon varchar(50) NOT NULL DEFAULT '',
  schet int NOT NULL
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Описание фирмы';

--
-- Create index `I1` on table `firma`
--
ALTER TABLE firma
ADD INDEX I1 (firma);

--
-- Create foreign key
--
ALTER TABLE firma
ADD CONSTRAINT FKschetf FOREIGN KEY (schet)
REFERENCES schet (n);

--
-- Create table `sklad`
--
CREATE TABLE sklad (
  N int UNSIGNED NOT NULL AUTO_INCREMENT,
  adres varchar(5000) NOT NULL,
  PRIMARY KEY (N)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `transport`
--
CREATE TABLE transport (
  n int NOT NULL AUTO_INCREMENT,
  nomer varchar(45) NOT NULL,
  marka varchar(45) NOT NULL,
  gruz float(12, 0) NOT NULL,
  god int NOT NULL,
  fio varchar(150) NOT NULL,
  data date NOT NULL,
  sklad int UNSIGNED NOT NULL,
  PRIMARY KEY (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `i5` on table `transport`
--
ALTER TABLE transport
ADD UNIQUE INDEX i5 (nomer);

--
-- Create foreign key
--
ALTER TABLE transport
ADD CONSTRAINT FK_transport_sklad FOREIGN KEY (sklad)
REFERENCES sklad (N);

--
-- Create table `tovar`
--
CREATE TABLE tovar (
  n int NOT NULL AUTO_INCREMENT,
  name varchar(500) NOT NULL DEFAULT 'Не указано',
  ed varchar(50) NOT NULL DEFAULT 'Не указано',
  cena int UNSIGNED NOT NULL,
  postav int NOT NULL,
  sklad int UNSIGNED NOT NULL,
  Kolvo int UNSIGNED NOT NULL,
  sort int UNSIGNED NOT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX idtovar (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Список товаров нормализованный';

--
-- Create index `i5` on table `tovar`
--
ALTER TABLE tovar
ADD INDEX i5 (name);

--
-- Create foreign key
--
ALTER TABLE tovar
ADD CONSTRAINT FK_tovar_sklad FOREIGN KEY (sklad)
REFERENCES sklad (N);

--
-- Create foreign key
--
ALTER TABLE tovar
ADD CONSTRAINT FKpostavt FOREIGN KEY (postav)
REFERENCES postav (n);

--
-- Create table `zakaz`
--
CREATE TABLE zakaz (
  n int NOT NULL AUTO_INCREMENT,
  data date NOT NULL,
  client int NOT NULL,
  tovar int NOT NULL,
  kolvo int NOT NULL DEFAULT 0,
  cena float(12, 0) NOT NULL,
  summa float(12, 0) NOT NULL,
  opl enum ('Y', 'N') NOT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX id_zakaz (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Список заказов п 10';

--
-- Create foreign key
--
ALTER TABLE zakaz
ADD CONSTRAINT FKclientz FOREIGN KEY (client)
REFERENCES klient (n);

--
-- Create foreign key
--
ALTER TABLE zakaz
ADD CONSTRAINT FKtovar FOREIGN KEY (tovar)
REFERENCES tovar (n);

--
-- Create table `nakladnaya`
--
CREATE TABLE nakladnaya (
  n int NOT NULL AUTO_INCREMENT,
  ntovar int NOT NULL,
  kolvo int UNSIGNED NOT NULL,
  summa float(12, 0) UNSIGNED NOT NULL,
  nklient int NOT NULL,
  PRIMARY KEY (n),
  UNIQUE INDEX idnaklad (n)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Накладные на товар';

--
-- Create foreign key
--
ALTER TABLE nakladnaya
ADD CONSTRAINT FK_nakladnaya_klient FOREIGN KEY (nklient)
REFERENCES klient (n);

--
-- Create foreign key
--
ALTER TABLE nakladnaya
ADD CONSTRAINT FKtovarn FOREIGN KEY (ntovar)
REFERENCES tovar (n);

--
-- Create table `kadry`
--
CREATE TABLE kadry (
  N int NOT NULL AUTO_INCREMENT,
  fio varchar(250) NOT NULL,
  dolg varchar(500) DEFAULT NULL,
  obraz enum ('Высшее', 'Среднеспециальное', 'Среднее', 'Базовое') NOT NULL,
  salary float(12, 0) UNSIGNED NOT NULL,
  data date NOT NULL,
  PRIMARY KEY (N),
  UNIQUE INDEX idkadr (N)
)
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci,
COMMENT = 'Сотрудники фирмы';

--
-- Create index `i2` on table `kadry`
--
ALTER TABLE kadry
ADD UNIQUE INDEX i2 (fio);

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;